# Generated by Django 3.0.1 on 2020-01-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=60)),
                ('mtype', models.CharField(max_length=60)),
                ('myear', models.CharField(max_length=60)),
                ('mename', models.CharField(max_length=60)),
                ('mdirector', models.CharField(max_length=20)),
                ('mrating', models.CharField(max_length=12)),
                ('mjs', models.CharField(max_length=1024)),
                ('mpicture', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('sex', models.CharField(max_length=12)),
                ('birthday', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
